### ISSUE TITLE
If loading dataset visualization is not instantaneous, it should show an activity indicator

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#2]
Relaited to #1 - while we can decrease the loading time, we might never quite eliminate it. If so, add an activity indicator or some other visual aide to let the user know an operation is in progress.

**Comment by darrenabbey** [comment]
A good idea, but we should wait to see what speed improvements we can do before worrying about how to do this in detail.

**Comment by vladimirg** [comment]
Visualizing datasets are now (almost) instantaneous, so this issue is no longer relevant.
