### ISSUE TITLE
The string 'fastq' in project names breaks analysis

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#24]
Specifically in FASTQ_2_trimming.sh (but also maybe elsewhere), the 'fastq' string is special and is replaced, so that the the final trimmed files get a bad destination name.

**Comment by ghost** [comment]
Changed files /scripts_Modules/FASTQ_1_trimming.sh and /scripts_Modules/FASTQ_2_trimming.sh making trimmed and residue name to replace last occurrence of .fastq
