### ISSUE TITLE
FTP uploads

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#3]
Allow users to upload the datasets via FTP, using any old FTP client (such as FileZilla or Cyberduck). The uploads must be resumable after an interruption or a pause.

**Comment by darrenabbey** [comment]
The ability to resume uploads would be dependent on the FTP protocol itself. Keeping the uploaded files in the location where they're uploaded would be all that is required for this.

The difficulty is in setting up FTP accounts and access for arbitrary users of the system.

An intermediate solution for the problem this would solve (minimizing cumulative transfer times) would be to copy every file uploaded through the current interface into a common directory (per-user) that can then later be accessed by that user. The initial upload of a data file would still be the slow step, but for reanalysis or new comparisons, the reduction in time would be dramatic.

**Comment by vladimirg** [comment]
Resuming in FTP does require a particular server configuration, though I agree that setting up the user permissions is probably the trickiest step.

For 1.0 I'd really like this solved for first-time uploads, not just re-analysis, because this is the first thing the user experiences, and if it fails, the user might abandon Ymap completely.

**Comment by darrenabbey** [comment]
Setting this up in a secure way remains problematic.  Lab directors have been consulted and agree that FTP drop access should be setup for an account only with direct negotiation with the lab.

It would be a simpler task on a dedicated server, but I don't think this is in the plans for the near future.

**Comment by vladimirg** [comment]
Why is FTP access so problematic?

I've also googled a little online, and found this: http://www.resumablejs.com . What do you think? On the face of it sounds like a better alternative. Most browsers have HTML5 support now (see http://caniuse.com/#feat=fileapi ).

**Comment by darrenabbey** [comment]
```
Problematic because the server administrators don’t want to open the system up in that way.
```
- darren

**Comment by vladimirg** [comment]
Alright, closing this in favor of resumable.js.
