### ISSUE TITLE
Whole-genome analysis crashes when chromosomes in reference genome are too short

### ISSUE THREAD

**Issue by vladimirg** [berman-lab/ymap#34]
Example: including mtDNA in C. ablicans reference genome. May be connected to lack of any reads in the chromosome, however this was also observed in another genome, Cyberlindnera fabianii, which currently has quite a few short (<=10,000 bp) contigs.

**Comment by darrenabbey** [comment]
YMAP may have difficulty generating figures if the chromosomes are too small. This issue was noted very early on in development and I thought I had resolved it in a robust manner. Exactly where the pipeline is crashing would help clarify if this is still an issue.

**Comment by vladimirg** [comment]
@GuyKha , please add the commit that fixes this issue and close it :)

**Comment by ghost** [comment]
Fixed by commit 644c15a4dab4166af30ffa79496ba47572cb6b5e
