### ISSUE TITLE
Wrong read of CNV

### ISSUE THREAD

**Issue by ghost** [berman-lab/ymap#48]
It appears there are places were the CNV read should be zero and yet it is as the baseline value.
For example in the following setting
Genome: Candida glabrata CBS138 (ver. 02-m04-r01)
DataSet: 195L_R_CCGTCC_L002_R1
hapmap: CBS_vs_BG2

in chromosome A in the middle there is a place with zero reads and it appears white yet the CNV at baseline. (image attached)

![fig cnv-snp-map 1](https://cloud.githubusercontent.com/assets/20476730/18437527/17156dc2-7906-11e6-855f-29638fd555f6.png)

**Comment by darrenabbey** [comment]
There is CNV data evident in that region, but there is no SNP ratio data.
The amount of CNV data is minimal, however,  which results in poor
numerical value determinations from the Gaussian fitting method used.

I think there is also be an explicit check for actual zero data in local
regions, which would then default to assumed baseline CNV values. This was
put in place to bypass an annoying divide-by-zero error for tiny regions of
zero-data that did not appear informative. I believe this is done in the
find_car_sizes function.

Usually, when a region is deleted there are some minimal reads mapped to
the region anyhow, which allows the visualization to show the appropriate
values. This prevented the bypass from being obviously a problem until now.
- D
