### ISSUE TITLE
Possible error in SNP coloring

### ISSUE THREAD

**Issue by ghost** [berman-lab/ymap#49]
When running YJBT07 with YJBT08 as parent chr2 is haploid and there is an area in the middle that is white, we should check if it supposed to be that way
![image](https://cloud.githubusercontent.com/assets/20476730/18864478/2f7bfb16-849f-11e6-91fc-61a9f0c795b1.png)

**Comment by darrenabbey** [comment]
It isn't clear from your description what the problem is. White in this
figure would represent a homozygous region in the parent dataset, which
won't necessarily be found in SC5314.

Overall, the figure illustrates a very high quality dataset.

**Comment by vladimirg** [comment]
We should look at the parent to check if that problematic region was homozygous in the parent. If it was, we do not expect it to be colored red, as there was no allelic ratio change from the homozygous diploid parent to the haploid child in this region.

**Comment by ghost** [comment]
I have checked the issue, the parent is indeed homozygous in this region.
Closing
