### ISSUE TITLE
Creating fire plot takes too much time

### ISSUE THREAD

**Issue by ghost** [berman-lab/ymap#50]
during processing3 in WGseq the function allelic_ratios_WGseq lines 196-237 takes to much time and causes the whole process to be very slow, the process is stuck especially on the num2str function we should change it, maybe use scanf with %d.
[profile_results.zip](https://github.com/berman-lab/ymap/files/495306/profile_results.zip)

**Comment by darrenabbey** [comment]
That is a very good idea. That section of code was written with convenience
in mind, not processing speed.

**Comment by ghost** [comment]
I have updated the code to work with text scan to process the putative or trimmed SNPs file which greatly improved the running time ([profile_results2.zip](https://github.com/berman-lab/ymap/files/588445/profile_results2.zip)).

As you can see the strcmp to check for comment lines took also very long time so I have changed it too and now there is no explicit check for comment line and it's implied by not finding the current chromosome in the chromosome list and the profile results show great improvement  -
[profile_results3.zip](https://github.com/berman-lab/ymap/files/588455/profile_results3.zip)

**Comment by darrenabbey** [comment]
I originally wanted there to be an explicit comment indicator, but it does
make sense the way you have done it. It now should more robustly fail well
under the input of malformatted text.

I'm glad there has been such a speed improvement.

**Comment by ghost** [comment]
Fixed by commits 0776c0ae3489f8d114fe1a63022f22f13c01de4f and c40c3d313e1b688d3d846aab29287c5418d6b207
