### ISSUE TITLE
Wrong segmentation in ChARM

### ISSUE THREAD

**Issue by ghost** [berman-lab/ymap#56]
Currently the [ChARM algorithm](https://github.com/berman-lab/ymap/wiki/ChARM-algorithm) does another smoothing after the differentiation filter, this results in wrong segmentation that appeared while running 195L_R_CCGTCC_L002_R1 with the hapmap CBS_vs_BG2.  
When running with the second smoothing filter (after differentiation) we get the following result:
![fig cnv-snp-map 1](https://cloud.githubusercontent.com/assets/20476730/19234163/7e2f41f2-8ef2-11e6-86e2-269f74ecced0.png)  
And without the second smoothing filter we get:
![fig cnv-snp-map 1](https://cloud.githubusercontent.com/assets/20476730/19234179/993402e4-8ef2-11e6-9d29-a57624357530.png)  

The segmentation has changed for chromosomes: A,C,G,I and now it's more accurate and since this is not part of the original ChARM article it will be removed in commit 644c15a4dab4166af30ffa79496ba47572cb6b5e (the commit will be merged to Integration and master once the matlab on lovelace will be updated)

**Comment by darrenabbey** [comment]
The CNV segmentation module could use being replaced with a more modern
algorithm. It would be worthwhile to look around and see what the best
method out there is right now. There may be software that can be integrated
without having to rewrite.

Another note: the copy number data in these figures looks very strange, so
it does not surprise me the existing algorithm may not be ideal.
