### ISSUE TITLE
FASTQC current version change

### ISSUE THREAD

**Issue by darrenabbey** [berman-lab/ymap#63]
While installing Ymap on my home system, I ran into an issue with the currently available version of FASTQC (v0.11.5). The program generates all of its files into a contained directory as before, but most of those files are now generated within a ZIP archive. This makes a text file which contains the FASTQ coding format inaccessible to the shell scripts which need it (for running GATK functions).

Adding the apparently new "--extract" option to each call of FASTQC resolved this issue for me. This change would need to be done in:
[Ymap_root]/scripts_seqModules/scripts_WGseq/project.paired_WGseq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_WGseq/project.single_WGseq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_ddRADseq/project.paired_ddRADseq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_ddRADseq/project.single_ddRADseq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_IonExpressSeq/project.paired_IonExpressSeq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_IonExpressSeq/project.single_IonExpressSeq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_RNAseq/project.paired_RNAseq.install_3.sh
[Ymap_root]/scripts_seqModules/scripts_RNAseq/project.single_RNAseq.install_3.sh

The specific lines can be found by searching for "fastqc".

**Comment by vladimirg** [comment]
The versions of all 3rd parties must be follow strictly using the [Setting up Ymap locally](https://github.com/berman-lab/ymap/wiki/Setting-up-Ymap-locally) guide. Anything else is unsupported.

**Comment by darrenabbey** [comment]
Older versions if FASTQC don't appear to be available.
-d

**Comment by vladimirg** [comment]
They're available, but hidden (don't know why). I've added the link for the Linux version to the installation guide. We actually should have added it sooner - thanks for catching this!

**Comment by darrenabbey** [comment]
Thanks! I had looked for it a few times and then shrugged and moved on.
- D
